language: swift
osx_image: xcode10
env:
  global:
  - IOS_SDK=iphonesimulator12.0
script:
  - xcodebuild -workspace Github\ Browser/Github\ Browser.xcworkspace -scheme 'Github Browser' -sdk $IOS_SDK build analyze